name: Debug

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch: {}

jobs:
  debug:
    runs-on: ubuntu-latest
    env:
      ENV: 'test'

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          mask-aws-account-id: 'no'

      - name: Load AWS Secrets Manager secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: ",portalxm-${{ env.ENV }}-secrets"
          parse-json-secrets: true
