name: Greetings

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch: {}

jobs:
  greetings:
    runs-on: ubuntu-latest
    environment: ${{ vars.ENVIRONMENT_STAGE }}

    steps:
      - uses: actions/checkout@v4

      - run: |
          docker build \
            --file Dockerfile \
            --tag greetings \
            --build-arg NAME=${{ vars.NAME }} \
            .
          docker run greetings
