name: Greetings

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch: {}

jobs:
  greetings:
    runs-on: ubuntu-latest
    environment: >-
      ${{
        (github.ref_name == 'main' && 'Production') ||
        (github.ref_name == 'staging' && 'Staging') ||
        'Development'
      }}

    steps:
      - uses: actions/checkout@v4

      - name: Build and run greetings
        run: |
          docker build \
            --file Dockerfile \
            --tag greetings \
            --build-arg NAME="${{ vars.NAME }}" \
            .
          docker run greetings
