name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "${GITHUB_REF_NAME}"
      - run: echo "${{ github.ref_name }}"
